/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.view;

import co.edu.unicauca.access.Factory;
import co.edu.unicauca.domain.entities.Project;
import co.edu.unicauca.domain.entities.User;
import co.edu.unicauca.domain.services.ProjectService;
import co.edu.unicauca.domain.services.UserService;
/*import co.edu.unicauca.domain.states.AceptadoState;
import co.edu.unicauca.domain.states.CerradoState;
import co.edu.unicauca.domain.states.EnEjecucionState;
import co.edu.unicauca.domain.states.RechazadoState;
import co.edu.unicauca.domain.states.RecibidoState;
 */
import co.edu.unicauca.infra.Messages;
import co.edu.unicauca.infra.dto.ProjectStatusRequest;
import co.edu.unicauca.infra.dto.ProjectStatusResponse;
import co.edu.unicauca.interfaces.IFrameFactory;
import co.edu.unicauca.interfaces.IRepository;

import co.edu.unicauca.main.Main;
import java.text.SimpleDateFormat;

//import co.edu.unicauca.interfaces.ProjectState;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yisus
 */
public class GUIGestionSofwareCoordinationProject extends javax.swing.JFrame {

    // private Map<String, ProjectState> estadosMap;
    private Project project;
    private ProjectService projectService;
    private User usuario;

    /**
     * Creates new form GUIGestionSofwareCoordinationProject
     */
    public GUIGestionSofwareCoordinationProject(ProjectService projectService, Project project, User usuario) {
        this.project = project;
        this.usuario = usuario;
        this.projectService = projectService;
        initComponents();
        //this.estadosMap = new HashMap<>();
        inicializarComboBox();
        cargarEstados();
        llenarCampos(project);
        this.usuario = usuario;
        cargarComentarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblProyectos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnombrecordinador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtInformacion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtobjetivos = new javax.swing.JTextField();
        txtresumen = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtempresa = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txttiempo = new javax.swing.JTextField();
        txtpresupuesto = new javax.swing.JTextField();
        txtPresupuesto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnguardarCambios = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        cbxestados = new javax.swing.JComboBox<>();
        txtmodificarestado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnEnviarComentario = new javax.swing.JButton();
        txtNuevoComentario = new javax.swing.JTextField();
        scrollComentarios = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("            Gestion de Proyectos Software Academicos  Ingenieria de Sistemas");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel7.setText("Empresas");

        jLabel8.setText("Estudiantes");

        lblProyectos.setText("Proyectos");
        lblProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProyectosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addGap(61, 61, 61)
                .addComponent(lblProyectos)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(lblProyectos))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Coordinador de sistemas");

        txtnombrecordinador.setEditable(false);
        txtnombrecordinador.setBackground(new java.awt.Color(247, 247, 247));
        txtnombrecordinador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtnombrecordinador.setBorder(null);
        txtnombrecordinador.setFocusable(false);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Opciones");

        jButton5.setBackground(new java.awt.Color(223, 224, 226));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtInformacion.setBackground(new java.awt.Color(9, 33, 103));
        txtInformacion.setForeground(new java.awt.Color(255, 255, 255));
        txtInformacion.setText("                                                                     Informacion del proyecto");
        txtInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInformacion.setEnabled(false);
        txtInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformacionActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(228, 228, 228));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Resumen:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Objetivos:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Descripcion:");

        txtobjetivos.setBackground(new java.awt.Color(228, 228, 228));
        txtobjetivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtobjetivos.setBorder(null);

        txtresumen.setEditable(false);
        txtresumen.setBackground(new java.awt.Color(228, 228, 228));
        txtresumen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtresumen.setBorder(null);

        txtdescripcion.setEditable(false);
        txtdescripcion.setBackground(new java.awt.Color(228, 228, 228));
        txtdescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtdescripcion.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtobjetivos)
                            .addComponent(txtresumen)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtobjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtresumen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanel5.setBackground(new java.awt.Color(228, 228, 228));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Empresa:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Tiempo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Presupuesto:");

        txtnombre.setEditable(false);
        txtnombre.setBackground(new java.awt.Color(228, 228, 228));
        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnombre.setBorder(null);

        txtempresa.setBackground(new java.awt.Color(228, 228, 228));
        txtempresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtempresa.setBorder(null);
        txtempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempresaActionPerformed(evt);
            }
        });

        txtfecha.setBackground(new java.awt.Color(228, 228, 228));
        txtfecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtfecha.setBorder(null);

        txttiempo.setBackground(new java.awt.Color(228, 228, 228));
        txttiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttiempo.setBorder(null);

        txtpresupuesto.setBackground(new java.awt.Color(228, 228, 228));
        txtpresupuesto.setBorder(null);
        txtpresupuesto.setEnabled(false);

        txtPresupuesto.setBackground(new java.awt.Color(228, 228, 228));
        txtPresupuesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPresupuesto.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPresupuesto))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtempresa))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Estado Actual:");

        btnguardarCambios.setBackground(new java.awt.Color(9, 33, 103));
        btnguardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        btnguardarCambios.setText("Guardar Cambios");
        btnguardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarCambiosActionPerformed(evt);
            }
        });

        txtestado.setEditable(false);
        txtestado.setBackground(new java.awt.Color(228, 228, 228));
        txtestado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtestado.setBorder(null);

        txtmodificarestado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmodificarestado.setText("Cambiar Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInformacion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtmodificarestado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxestados, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnguardarCambios)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnguardarCambios)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodificarestado))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel15.setText("Comentarios del proyecto");

        btnEnviarComentario.setBackground(new java.awt.Color(9, 33, 103));
        btnEnviarComentario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarComentario.setText("Enviar");
        btnEnviarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComentarioActionPerformed(evt);
            }
        });

        txtNuevoComentario.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevoComentario.setForeground(new java.awt.Color(0, 0, 0));

        scrollComentarios.setBackground(new java.awt.Color(255, 255, 255));
        scrollComentarios.setForeground(new java.awt.Color(0, 0, 0));

        txtComentarios.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        scrollComentarios.setViewportView(txtComentarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollComentarios)
                            .addComponent(txtNuevoComentario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviarComentario)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(590, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarComentario)
                    .addComponent(txtNuevoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnombrecordinador)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3)
                        .addGap(148, 148, 148))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtnombrecordinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresaActionPerformed

    private void txtInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformacionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        Main.mostrarLogin();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnguardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarCambiosActionPerformed

        cambiarEstado();
    }//GEN-LAST:event_btnguardarCambiosActionPerformed

    private void lblProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProyectosMouseClicked
        GUIGestionSofwareCoordination instance = new GUIGestionSofwareCoordination(projectService, usuario);
        instance.setExtendedState(JFrame.NORMAL);
        instance.setVisible(true);
        this.dispose();;

    }//GEN-LAST:event_lblProyectosMouseClicked

    private void btnEnviarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComentarioActionPerformed
        try {
            String mensaje = txtNuevoComentario.getText().trim();

            if (mensaje.isEmpty()) {
                Messages.showMessageDialog("El comentario no puede estar vacío", "Advertencia");
                return;
            }

            if (project.getId() > Integer.MAX_VALUE || usuario.getId() > Integer.MAX_VALUE) {
                Messages.showMessageDialog("ID de proyecto o usuario demasiado grande", "Error");
                return;
            }

            int projectId = (int) project.getId();
            int userId = usuario.getId().intValue();

            System.out.println("Enviando comentario - Proyecto: " + projectId
                    + ", Usuario: " + userId
                    + ", Mensaje: " + mensaje);

            boolean exito = projectService.addComment(
                    projectId,
                    userId,
                    usuario.getUsername(),
                    mensaje
            );

            if (exito) {
                Messages.showMessageDialog("Comentario agregado correctamente", "Éxito");
                txtNuevoComentario.setText("");
                cargarComentarios();
            } else {
                Messages.showMessageDialog("No se pudo agregar el comentario", "Error");
            }
        } catch (Exception e) {
            e.printStackTrace();
            Messages.showMessageDialog("Error al enviar comentario: " + e.getMessage(), "Error");
        }

    }//GEN-LAST:event_btnEnviarComentarioActionPerformed
    private void llenarCampos(Project proyecto) {
        txtnombrecordinador.setText(usuario.getUsername());
        txtnombre.setText(proyecto.getNombre());
        txtempresa.setText(proyecto.getNombreEmpresa());
        txtfecha.setText(proyecto.getFechaEntregadaEsperada());
        txttiempo.setText(String.valueOf(proyecto.getTiempoMaximo()));
        txtPresupuesto.setText(String.valueOf(proyecto.getPresupuesto()));
        txtobjetivos.setText(proyecto.getObjetivo());
        txtresumen.setText(proyecto.getResumen());
        txtdescripcion.setText(proyecto.getDescripcion());
        txtestado.setText(proyecto.getEstadoString());
    }

    private void inicializarComboBox() {
        // No cargamos nada fijo aquí
        cbxestados.setModel(new DefaultComboBoxModel<>());
        actualizarOpcionesEstado(project.getEstadoString());
    }

    private void cargarEstados() {
        /* estadosMap.put("RECIBIDO", new RecibidoState());
        estadosMap.put("ACEPTADO", new AceptadoState());
        estadosMap.put("EJECUCION", new EnEjecucionState());
        estadosMap.put("CERRADO", new CerradoState());
        estadosMap.put("RECHAZADO", new RechazadoState());
         */
    }

    private void actualizarOpcionesEstado(String estadoActual) {
        cbxestados.removeAllItems(); // Limpia el JComboBox

        switch (estadoActual) {
            case "RECIBIDO":
                cbxestados.addItem("ACEPTADO");
                cbxestados.addItem("RECHAZADO");
                break;
            case "ACEPTADO":
                cbxestados.addItem("EJECUCION");
                break;
            case "RECHAZADO":
                cbxestados.addItem("No hay opciones disponibles");
                break;
            case "EN EJECUCION":
                cbxestados.addItem("CERRADO");
                break;
            case "CERRADO":
                cbxestados.addItem("No hay opciones disponibles");
                break;
            default:
                cbxestados.addItem("No hay opciones disponibles");
                break;
        }

    }

    private void cambiarEstado() {
        String nuevoEstadoStr = (String) cbxestados.getSelectedItem();
        ProjectStatusResponse projectStatusResponse = null;

        if (nuevoEstadoStr == null || nuevoEstadoStr.equals("No hay opciones disponibles")) {
            Messages.showMessageDialog("No se puede cambiar a este Estado", "Error");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de cambiar el estado del proyecto a " + nuevoEstadoStr + "?",
                "Confirmar cambio de estado", JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        ProjectStatusRequest request = new ProjectStatusRequest();
        request.setProjectId(project.getId());

        if (nuevoEstadoStr.equals("RECHAZADO")) {
            request.setAction("noAvanzar");

        } else {
            request.setAction("avanzar");
        }

        projectStatusResponse = projectService.updateProjectStatus(request);

        txtestado.setText(projectStatusResponse.getEstado());
        actualizarOpcionesEstado(projectStatusResponse.getEstado());
        Messages.showMessageDialog(projectStatusResponse.getMensaje(), "Estado Actualizado");

        /*ProjectState estadoActual = project.getEstado();
        ProjectState nuevoEstado = null;

        if (nuevoEstadoStr.equals("RECHAZADO")) {
            nuevoEstado = estadoActual.NoAvanzaEstado(project);
        } else {
            nuevoEstado = estadoActual.avanzarEstado(project);
        }

        // Validación para evitar inconsistencias
        if (!nuevoEstado.getEstado().equals(nuevoEstadoStr)) {
            Messages.showMessageDialog("No se puede avanzar a este estado", "Error");
            return;
        }

        project.setEstado(nuevoEstado);

        boolean cambioExitoso = projectService.cambiarEstado(project, nuevoEstado);

        if (cambioExitoso) {
            txtestado.setText(project.getEstadoString());
            actualizarOpcionesEstado(project.getEstadoString());
            Messages.showMessageDialog("Estado Actualizado Correctamente", "Estado Actualizado");
        } else {
            Messages.showMessageDialog("No se pudo Actualizar el Estado", "Error");
        }
         */
    }

    private void cargarComentarios() {
        try {
            System.out.println("Intentando cargar comentarios para proyecto ID: " + project.getId());

            if (project.getId() > Integer.MAX_VALUE) {
                Messages.showMessageDialog("ID de proyecto demasiado grande", "Error");
                return;
            }
            int projectId = (int) project.getId();

            List<Map<String, String>> comentarios = projectService.getCommentsByProject(projectId);

            System.out.println("Comentarios recibidos: " + (comentarios != null ? comentarios.size() : "null"));

            if (comentarios == null || comentarios.isEmpty()) {
                txtComentarios.setText("No hay comentarios para este proyecto.");
            } else {
                mostrarComentarios(comentarios);
            }
        } catch (Exception e) {
            e.printStackTrace();
            txtComentarios.setText("Error al cargar comentarios: " + e.getMessage());
        }
    }

    private void mostrarComentarios(List<Map<String, String>> comentarios) {
        StringBuilder sb = new StringBuilder();

        for (Map<String, String> comentario : comentarios) {
            sb.append("[")
                    .append(comentario.get("timestamp"))
                    .append("] ")
                    .append(comentario.get("coordinatorName"))
                    .append(":\n")
                    .append(comentario.get("message"))
                    .append("\n\n");
        }

        txtComentarios.setText(sb.toString());
        txtComentarios.setCaretPosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarComentario;
    private javax.swing.JButton btnguardarCambios;
    private javax.swing.JComboBox<String> cbxestados;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblProyectos;
    private javax.swing.JScrollPane scrollComentarios;
    private javax.swing.JTextPane txtComentarios;
    private javax.swing.JTextField txtInformacion;
    private javax.swing.JTextField txtNuevoComentario;
    private javax.swing.JTextField txtPresupuesto;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JLabel txtmodificarestado;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombrecordinador;
    private javax.swing.JTextField txtobjetivos;
    private javax.swing.JTextField txtpresupuesto;
    private javax.swing.JTextField txtresumen;
    private javax.swing.JTextField txttiempo;
    // End of variables declaration//GEN-END:variables
}
